# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engWord', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='basic',
            new_name='text',
        ),
    ]
