# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engWord', '0002_auto_20160422_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='basic_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engWord.Word'),
        ),
    ]
