# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engWord', '0003_word_basic_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('src', models.CharField(max_length=15)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engWord.Word')),
            ],
        ),
    ]
