# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engWord', '0004_worddetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='worddetail',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
